# Project Spec:
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: ToDoAuth

include:
  - ../xcodegen/framework.yml

options:
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: 14.0

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 9.0.0

targets:
  ToDoAuth:
    templates:
      - ModularFramework
    sources:
      - Framework
    dependencies:
      - package: Firebase
        product: FirebaseAuth
