# Project Spec:
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: ToDoStore

include:
  - ../xcodegen/framework.yml

options:
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: 14.0

packages:
  ReSwift:
    url: https://github.com/ReSwift/ReSwift
    majorVersion: 6.0.0
  ReSwiftThunk:
    url: https://github.com/ReSwift/ReSwift-Thunk
    majorVersion: 2.0.0

targets:
  ToDoStore:
    templates:
      - ModularFramework
    sources:
      - Framework
    dependencies:
      - package: ReSwift
      - package: ReSwiftThunk
      - framework: ToDoShared.framework
        implicit: true
      - framework: ToDoDatabase.framework
        implicit: true
