# Project Spec:
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: ToDo

options:
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: 14.0
  createIntermediateGroups: true
  preGenCommand: |

    # mint is needed to manage packages used by this project
    if ! command -v mint &> /dev/null
    then
      echo "=========== !!!ATTENTION!!! ==========="
      echo "mint could not be found"
      echo "Please install using brew:"
      echo "brew install mint"
      echo "OR"
      echo "https://github.com/yonaskolb/Mint#installing"
      echo "=========== !!!ATTENTION!!! ==========="
      exit 0
    fi

    # Generated files. We need to create an empty file for xcodegen such that it is added to the project and proper target
    # Otherwise the file will not be in xcode after the generation
    touch ToDo/Resources/Generated/LocalizedStrings.swift
    touch ToDo/Resources/Generated/Images.swift
    touch ToDo/Resources/Generated/Colors.swift

  postGenCommand: |
    # Check if we are on an M1 mac
    if [[ -f Podfile ]]; then
      if [[ $(uname -p) == 'arm' ]]; then
        arch -x86_64 pod install --repo-update
      else
        pod install --repo-update
      fi
    fi

fileGroups:
  # - README.md
  # - project.yml
  # - Mintfile
  # - .swift-version
  # - .swiftlint.yml
  # - .swiftformat

packages:
  SFSafeSymbols:
    url: https://github.com/SFSafeSymbols/SFSafeSymbols
    majorVersion: 4.0.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 9.0.0
  Quick:
    url: https://github.com/Quick/Quick
    majorVersion: 5.0.0
  Nimble:
    url: https://github.com/Quick/Nimble
    majorVersion: 10.0.0

targets:
  ToDo:
    type: application
    platform: iOS
    entitlements:
      path: ToDo/Resources/ToDo.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
    info:
      path: ToDo/Resources/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: "Launch Screen.storyboard"
        UIApplicationShortcutItems:
          - UIApplicationShortcutItemType: AddTodo
            UIApplicationShortcutItemIconSymbolName: plus.circle
            UIApplicationShortcutItemIconType: UIApplicationShortcutItemIconTypePlus
            UIApplicationShortcutItemTitle: Add Todo
    settings:
      base:
        # iPhone only
        TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: HQR253M6PT
        PRODUCT_BUNDLE_IDENTIFIER: com.dcarmo.ToDo
        PRODUCT_NAME: ToDo
        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
        SWIFT_STRICT_CONCURRENCY: complete
    sources:
      - ToDo
    preBuildScripts:
      - name: "[TS] SwiftGen/SwiftGen"
        basedOnDependencyAnalysis: false
        script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which mint > /dev/null; then
            mint run SwiftGen/SwiftGen@6.6.2
          else
            echo "WARNING: mint or SwiftGen not installed, use `brew install mint` then `mint bootstrap` to install tools"
          fi
      - name: "[TS] nicklockwood/SwiftFormat"
        basedOnDependencyAnalysis: false
        script: |
          #export PATH="$PATH:/opt/homebrew/bin"
          #if which mint > /dev/null; then
          #  mint run nicklockwood/SwiftFormat@0.50.0 --config "${SRCROOT}/../.swiftformat" "$SRCROOT"
          #else
          #  echo "WARNING: mint or SwiftFormat not installed, use `brew install mint` then `mint bootstrap` to install tools"
          #fi
      - name: "[TS] realm/SwiftLint"
        basedOnDependencyAnalysis: false
        script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which mint > /dev/null; then
            mint run realm/SwiftLint@0.49.1 --config "${SRCROOT}/../.swiftlint.yml"
          else
            echo "WARNING: mint or SwiftLint not installed, use `brew install mint` then `mint bootstrap` to install tools"
          fi
    scheme: {}
    dependencies:
      - package: SFSafeSymbols
      - package: Firebase
        product: FirebaseDatabase
      - framework: ToDoDatabase.framework
        implicit: true
      - framework: ToDoShared.framework
        implicit: true
      - framework: ToDoStore.framework
        implicit: true
      - target: ToDoWidget
        codeSign: false
        embed: true

  ToDoTests:
    type: bundle.unit-test
    platform: iOS
    entitlements:
      path: ToDoTests/Resources/ToDo.entitlements
    info:
      path: ToDoTests/Resources/Info.plist
    sources:
      - ToDoTests
    dependencies:
      - target: ToDo
      - package: Quick
      - package: Nimble
    scheme:
      testTargets:
        - ToDo
        - ToDoTests

  ToDoUITests:
    type: bundle.ui-testing
    platform: iOS
    entitlements:
      path: ToDoTests/Resources/ToDo.entitlements
    info:
      path: ToDoTests/Resources/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dcarmo.ToDo.UITests
      PRODUCT_NAME: ToDoUITests
    sources:
      - ToDoUITests
    dependencies:
      - target: ToDo
    scheme:
      testTargets:
        - ToDo
        - ToDoUITests

  ToDoWidget:
    type: app-extension
    platform: iOS
    info:
      path: Widget/Resources/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: "com.apple.widgetkit-extension"
    settings:
      base:
        # iPhone only
        TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: HQR253M6PT
        PRODUCT_BUNDLE_IDENTIFIER: com.dcarmo.ToDo.Widget
        PRODUCT_NAME: ToDo Widget
        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
    sources:
      - Widget
    scheme: {}
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
      - package: SFSafeSymbols
      - framework: ToDoDatabase.framework
        implicit: true
      - framework: ToDoShared.framework
        implicit: true

  ToDoWatch:
    type: application.watchapp
    platform: watchOS
    deploymentTarget:
      watchOS: 9.1
    settings:
      base:
        # iPhone only
        TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: HQR253M6PT
        PRODUCT_BUNDLE_IDENTIFIER: com.dcarmo.ToDo.Watch
        PRODUCT_NAME: ToDo Watch
        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
    sources:
      - WatchApp
    dependencies:
      - sdk: WatchKit.framework
      - framework: ToDoDatabase.framework
        implicit: true
      - framework: ToDoShared.framework
        implicit: true
