# Project Spec:
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: ToDoShared

include:
  - ../xcodegen/framework.yml

options:
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: 14.0

targets:
  ToDoShared:
    templates:
      - ModularFramework
    sources:
      - Framework
