# Project Spec:
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: ToDoShared

options:
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: 14.0

targets:
  ToDoShared:
    type: framework
    platform: iOS
    settings:
      base:
        # iPhone only
        TARGETED_DEVICE_FAMILY: 1
        # Fix issue with framework requiring signing. Likely need to find a better fix for this.
        CODE_SIGNING_ALLOWED: "NO"
        # Versioning
        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
    sources:
      - Framework
    preBuildScripts:
      - name: "[TS] nicklockwood/SwiftFormat"
        basedOnDependencyAnalysis: false
        script: |
          #export PATH="$PATH:/opt/homebrew/bin"
          #if which mint > /dev/null; then
          #  mint run nicklockwood/SwiftFormat@0.50.0 --config "${SRCROOT}/../.swiftformat" "$SRCROOT"
          #else
          #  echo "WARNING: mint or SwiftFormat not installed, use `brew install mint` then `mint bootstrap` to install tools"
          #fi
      - name: "[TS] realm/SwiftLint"
        basedOnDependencyAnalysis: false
        script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which mint > /dev/null; then
            mint run realm/SwiftLint@0.49.1 --config "${SRCROOT}/../.swiftlint.yml"
          else
            echo "WARNING: mint or SwiftLint not installed, use `brew install mint` then `mint bootstrap` to install tools"
          fi
